_Base_Config: 'config/miga/miga_graphTrans.yaml'
gpus: '4'
batch_size: 128
runner: NoiseGraphPretrainRunner
atom_to_what: for_diffusion
make_one_hot: True
num_workers: 32
epochs: 2000
run:
  task: miga_transformer_b128_l3_atom60_vis
  run_type: embedding_vis
  embedding_save_dir: "/rhome/lianyu.zhou/cache/cluster_test_set_gformer_l3_b256_atom60"
  embedding_dir: '/rhome/lianyu.zhou/cache/cluster_test_set_gformer_l3_b256_atom60'
  resume: '/rhome/lianyu.zhou/cache/MIGA/miga_transformer_b128_l3_atom60/2023-2-4-15-26-18/weight/model_700.pth'

