# Running Configuration ######################################################
run:
    n_epoch: 1000
    ############################################################################
    task: temp/temp
    save_path: '/rhome/lianyu.zhou/cache/MIGA/{}/{}'
    FP16: True
    save_epoch: []#'[50 * i for i in range(10, 600)]'

# Validation Configuration ######################################################
valid:
    n_valid_per_epoch: 1
    data_type: test